apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingapi-deployment
  minReplicas: 2 #Min replica count
  maxReplicas: 3  #Max replica count
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 #Target CPU utilization
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingclient-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingclient-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

