name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Docker Buildx (to enable advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: kkshoppingappacr.azurecr.io
          username: kkshoppingappacr
          password: +onXKxOHOzKDsQnzS6UUXfONNO/sNJ3P7mLex4STGA+ACRBnsA9i
      
      # Step 4: Build and push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -f Shopping/Shopping.API/Dockerfile -t kkshoppingappacr.azurecr.io/shoppingapidepl:${{ github.run_id }} .
          docker push kkshoppingappacr.azurecr.io/shoppingapidepl:${{ github.run_id }}
