name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # Define variables for login-server and image repository
      LOGIN_SERVER: kkshoppingappacr.azurecr.io
      IMAGE_REPOSITORY: shoppingapidepl
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (to enable advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      
      # Step 4: Build and push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -f Shopping/Shopping.API/Dockerfile -t ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_REPOSITORY }}:${{ github.run_id }} Shopping/Shopping.API
          docker push ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_REPOSITORY }}:${{ github.run_id }}
